name: wes_part2_env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alsa-lib=1.2.8
  - bbmap=39.01
  - bedtools=2.23.0
  - binutils_impl_linux-64=2.40
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - curl=7.87.0
  - expat=2.5.0
  - fgbio=2.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gatk4=4.4.0.0
  - gcc_impl_linux-64=12.2.0
  - gettext=0.21.1
  - gfortran_impl_linux-64=12.2.0
  - giflib=5.2.1
  - graphite2=1.3.13
  - gsl=2.7
  - gxx_impl_linux-64=12.2.0
  - harfbuzz=6.0.0
  - htslib=1.17
  - icu=70.1
  - jpeg=9e
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - krb5=1.20.1
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcups=2.3.3
  - libcurl=7.87.0
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-devel_linux-64=12.2.0
  - libgcc-ng=12.2.0
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libsanitizer=12.2.0
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=12.2.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxml2=2.10.3
  - libzlib=1.2.13
  - make=4.3
  - ncurses=6.3
  - openjdk=17.0.3
  - openssl=1.1.1t
  - pango=1.50.14
  - pbzip2=1.1.13
  - pcre2=10.40
  - pip=23.0.1
  - pixman=0.40.0
  - pthread-stubs=0.4
  - python=3.11.0
  - r-base=4.2.2
  - r-cli=3.6.0
  - r-colorspace=2.1_0
  - r-crayon=1.5.2
  - r-ellipsis=0.3.2
  - r-fansi=1.0.4
  - r-farver=2.1.1
  - r-ggplot2=3.4.1
  - r-glue=1.6.2
  - r-gtable=0.3.3
  - r-isoband=0.2.7
  - r-labeling=0.4.2
  - r-lattice=0.20_45
  - r-lifecycle=1.0.3
  - r-magrittr=2.0.3
  - r-mass=7.3_58.3
  - r-matrix=1.5_3
  - r-mgcv=1.8_42
  - r-munsell=0.5.0
  - r-nlme=3.1_162
  - r-pillar=1.9.0
  - r-pkgconfig=2.0.3
  - r-r6=2.5.1
  - r-rcolorbrewer=1.1_3
  - r-rlang=1.1.0
  - r-scales=1.2.1
  - r-tibble=3.2.1
  - r-utf8=1.2.3
  - r-vctrs=0.6.1
  - r-viridislite=0.4.1
  - r-withr=2.5.0
  - readline=8.1.2
  - samtools=1.16.1
  - sed=4.8
  - setuptools=67.6.0
  - sysroot_linux-64=2.12
  - tk=8.6.12
  - tktable=2.10
  - tzdata=2022g
  - wheel=0.40.0
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
prefix: /home/ubuntu/miniconda3/envs/wes_part2_env
